### ISSUE TITLE
Fix could not connect error not being told to user

### ISSUE THREAD

**Issue by JacobFischer** [siggame/Joueur.cpp#4]
Run the game client and try to connect to a game server that does not exist.
```
An error occurred:
Error during initialization.
```

You will get an error but no details on _why_ it was unexpected, even though we know when we are trying to connect.

**Comment by KendallHarter** [comment]
Realized that this was still open even though it was fixed by a25e55fdb186aab007c229dfba0d0464a01f8121
Closing.
