### ISSUE TITLE
Seg fault on invalid function call

### ISSUE THREAD

**Issue by JacobFischer** [siggame/Joueur.cpp#7]
If you try to do an invalid action, e.g. move to `nullptr` it is syntactically valid, and will compile. It should also work and send to the game server, to the game server can send back an invalid message.

Currently one of two things happens:

1. It seg faults on the function call, the game server doesn't even get the command
e.g. https://github.com/siggame/Joueur.cpp/blob/0ded377c020b00edcd29cbc4480362904bbdcd6f/games/stumped/ai.cpp#L111 cange path.get(0) to `nullptr`.

2. It segfaults or claims a delta merge error (with no additional details) upon getting the invalid back.
So let's say this is our stumped AI in run_turn():
```cpp
    std::cout << "My turn " << game->current_turn << std::endl;

    for(const auto beaver : this->player->beavers) {
        if(beaver->tile->tile_north) {
            beaver->move(beaver->tile->tile_north);
        }
    }

    std::cout << "Done with our turn" << std::endl;
    return true;
```

This will eventually break when tile north is blocked (--printIO flag on):
```
FROM SERVER <-- {"event":"order","data":{"name":"runTurn","index":23,"args":[]}}
My turn 23
TO SERVER --> {"event": "run", "data": {"functionName": "move", "caller": {"id": "676"}, "args": {"tile":{"id":349}}}, "sentTime": 1492287399610}
FROM SERVER <-- {"event":"invalid","data":{"message":"Tile (17, 0) #349 is already occupied by Beaver #675."}}
Invalid: Tile (17, 0) #349 is already occupied by Beaver #675.
FROM SERVER <-- {"event":"delta","data":{"gameObjects":{"1":{"timeRemaining":70787870141}}}}
FROM SERVER <-- {"event":"ran"}
[Bad_response] An error occured:
Unknown JSON type received in a delta.
```

Both of these were problems for C++ competitors in Stumped. I'm not sure if they are actually related, but they both have similar causes (invalid actions) so I'm lumping them into one bug.

**Comment by KendallHarter** [comment]
Second bug may still be present, unable to test at this time.
